apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  creationTimestamp: null
  name: function-mystifying-karol3
  namespace: default
spec:
  runtime: python39
  source: |-
    def main(event, context):
        return "hello world"

